name: Sincronización completa del repositorio

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Ejecutar cada 5 minutos

jobs:
  sincronizar:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar usuario Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Detectar cambios en la carpeta
        run: |
          git add --all
          if git status --porcelain | grep -qE '^( A| M| D| R) '; then
            echo "Cambios detectados en la carpeta, realizando commit."
            git commit -m "Sincronización automática: archivos nuevos, renombrados y eliminados"
            git push origin main
          else
            echo "No hay cambios que sincronizar."
            exit 0
          fi