name: Sincronizar repositorio

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Ejecutar cada 5 minutos

jobs:
  sincronizar:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar usuario Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit y push de cambios
        run: |
          git add .
          git commit -m "Sincronización automática"
          git push origin main