name: Sincronizar repositorio

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Ejecutar cada 5 minutos

jobs:
  sincronizar:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar usuario Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Agregar y verificar archivos nuevos
        run: |
          git add --all
          if git status | grep -q "Untracked files"; then
            echo "Archivos nuevos detectados, realizando commit."
            git commit -m "Sincronización automática con archivos nuevos"
            git push origin main
          else
            echo "No hay archivos nuevos para sincronizar."
            exit 0
          fi